thread_num: 8
model:
  frag_types:
  - b
  - y
  - b_modloss
  - y_modloss
  max_frag_charge: 2
model_mgr:
  predict:
    batch_size_ms2: 512
    batch_size_rt_ccs: 1024
    default_nce: 0.3
    default_instrument: Lumos
    verbose: True
  fine_tune:
    epoch_ms2: 10
    epoch_rt_ccs: 20
    grid_nce_search: True
    grid_nce_first: 0.15
    grid_nce_last: 0.45
    grid_nce_step: 0.03
    grid_instrument: ['Lumos']
percolator:
  require_model_tuning: True
  raw_num_to_tune: 8
  psm_num_to_tune_ms2: 5000
  psm_num_per_mod_to_tune_ms2: 100
  psm_num_to_tune_rt_ccs: 5000
  mod_psm_num_to_tune_rt_ccs: 100
  top_n_mods_to_tune: 10
  model_type: regular # or phos, or HLA
  mask_modloss: True

  require_raw_specific_tuning: True
  raw_specific_ms2_tuning: False
  psm_num_per_raw_to_tune: 200
  epoch_per_raw_to_tune: 5

  multiprocessing: True

  ms2_ppm: True
  ms2_tol: 20
  max_perc_train_sample: 50000
  min_perc_train_sample: 100

  ml_type: logistic_regression
  ml_type_choices:
    - logistic_regression
    - lr
    - random_forest
    - rf
  ml_iter_num: 5
  cv_fold: 1
  fdr: 0.01
  fdr_level: psm
  per_raw_fdr: False
  fdr_level_choices:
    - psm
    - precursor
    - peptide
    - sequence
  frag_types: ['b_z1','b_z2','y_z1','y_z2']
  input_files:
    psm_type: alphapept
    psm_type_choices:
      - alphapept
      - pfind
      - maxquant
      - msfragger_pepxml
    psm_files: []
    raw_type: alphapept_hdf
    psm_type_choices:
      - hdf
      - mgf
      - thermo_raw
      - mzml
    raw_files: []
    other_score_column_mapping:
      alphapept: {}
      pfind: 
        raw_score: Raw_Score
      msfragger:
        hyperscore: hyperscore
        nextscore: nextscore
      maxquant: {}
spec_lib:
  input:
    type: pfind3
    accepted_types:
    - fasta
    - pfind3
    - maxquant
    - alphapept
    files: 
    - xxx.fasta
    ms_files:
    - /x/xx/xxx.raw
    instrument: QE
    ce: 27
    fasta:
      max_miss_cleave: 3
      fixmod: 
      - Carbamidomethyl@C
      varmod:
      - Oxidation@M
      min_varmod: 0
      max_varmod: 1
      target_mod: []
      min_target_mod: 0
      max_target_mod: 2
  output:
    type: spectronaut
    accepted_types:
    - spectronaut
    - diann
    - msp
    library: xxx.csv
    min_fragment_mz: 300
    max_fragment_mz: 2000
    min_intensity: 0.1
    least_n_peaks: 6
    max_ion_charge: 2
    ion_types:
    - b
    - y
    - b-modloss
    - y-modloss
    min_precursor_charge: 2
    max_precursor_charge: 4
    min_precursor_mz: 400
    max_precursor_mz: 1200
    min_peptide_len: 6
    max_peptide_len: 60
    decoy: no_decoy
    modname_as_mass: false