thread_num: 8
model:
  frag_types:
  - b
  - y
  - b_modloss
  - y_modloss
  max_frag_charge: 2
percolator:
  cv_fold: 1
  max_train_sample: 50000
  min_train_sample: 100
  ms2_ppm: True
  ms2_tol: 20
spec_lib:
  input:
    type: pfind3
    accepted_types:
    - fasta
    - pfind3
    - maxquant
    - alphapept
    files: 
    - xxx.fasta
    ms_files:
    - /x/xx/xxx.raw
    instrument: QE
    ce: 27
    fasta:
      max_miss_cleave: 3
      fixmod: 
      - Carbamidomethyl@C
      varmod:
      - Oxidation@M
      min_varmod: 0
      max_varmod: 1
      target_mod: []
      min_target_mod: 0
      max_target_mod: 2
  output:
    type: spectronaut
    accepted_types:
    - spectronaut
    - diann
    - msp
    library: xxx.csv
    min_fragment_mz: 300
    max_fragment_mz: 2000
    min_intensity: 0.1
    least_n_peaks: 6
    max_ion_charge: 2
    ion_types:
    - b
    - y
    - b-modloss
    - y-modloss
    min_precursor_charge: 2
    max_precursor_charge: 4
    min_precursor_mz: 400
    max_precursor_mz: 1200
    min_peptide_len: 6
    max_peptide_len: 60
    decoy: no_decoy
    modname_as_mass: false